export const ALL_FACILITIES_REQUEST = "ALL_FACILITIES_REQUEST";
export const ALL_FACILITIES_SUCCESS = "ALL_FACILITIES_SUCCESS";
export const ALL_FACILITIES_FAIL = "ALL_FACILITIES_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";