export const ALL_FACILITIES_TYPE_REQUEST = "ALL_FACILITIES_TYPE_REQUEST";
export const ALL_FACILITIES_TYPE_SUCCESS = "ALL_FACILITIES_TYPE_SUCCESS";
export const ALL_FACILITIES_TYPE_FAIL = "ALL_FACILITIES_TYPE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";