export const ALL_HOTEL_TYPE_REQUEST = "ALL_HOTEL_TYPE_REQUEST";
export const ALL_HOTEL_TYPE_SUCCESS = "ALL_HOTEL_TYPE_SUCCESS";
export const ALL_HOTEL_TYPE_FAIL = "ALL_HOTEL_TYPE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";