export const ALL_HOTEL_REQUEST = "ALL_HOTEL_REQUEST";
export const ALL_HOTEL_SUCCESS = "ALL_HOTEL_SUCCESS";
export const ALL_HOTEL_FAIL = "ALL_HOTEL_FAIL";

export const FILTER_HOTEL_REQUEST = "FILTER_HOTEL_REQUEST";
export const FILTER_HOTEL_SUCCESS = "FILTER_HOTEL_SUCCESS";
export const FILTER_HOTEL_FAIL = "FILTER_HOTEL_FAIL";

export const SET_SELECTED_HOTEL_ID = "SET_SELECTED_HOTEL_ID";

export const HOTEL_DETAILS_REQUEST = "HOTEL_DETAILS_REQUEST";
export const HOTEL_DETAILS_SUCCESS = "HOTEL_DETAILS_SUCCESS";
export const HOTEL_DETAILS_FAIL = "HOTEL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";