// constants/serviceConstants.js
export const UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_FAIL = "UPDATE_SERVICE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Định nghĩa các hằng số action cho Service
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_FAIL = "CREATE_SERVICE_FAIL";

export const GET_HOTEL_ID_REQUEST = "GET_HOTEL_ID_REQUEST";
export const GET_HOTEL_ID_SUCCESS = "GET_HOTEL_ID_SUCCESS";
export const GET_HOTEL_ID_FAIL = "GET_HOTEL_ID_FAIL";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";